# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Chaplin
email: ankitsultana@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Chaplin is a black and white theme for <span>Jekyll</span>. It was made by 
  Ankit Sultana.
baseurl: "/Chaplin" # the subpath of your site, e.g. /blog
url: "http://bk2dcradle.gitub.io" # the base hostname & protocol for your site
twitter_username: AnkitSultana
github_username:  bk2dcradle

permalink:          /:year/:title.html

# Build settings
markdown: kramdown

comments: true

paginate: 4
paginate_path: "/page/:num"
comments: true

gems:
  - jekyll-paginate

sass:
  style:            compressed
  sass_dir:         _sass

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
