# User Settings | Edit these according to your site

title: dataBlog
email: choul.raj@gmail.com
author: Raj Nikhil Choul

description: > # this means to ignore newlines until "baseurl:"
  Chaplin is a minimalistic, mobile friendly theme for Jekyll.
  The Documentation for it is available on this website itself. 
  You can check out the source on <a href="http://github.com/bk2dcradle/Chaplin" class="deactivate-link"><span> GitHub </span></a>

url: "https://rajnikhil.gitub.io" # the base hostname & protocol for your site
baseurl: "/dataBlog" # the subpath of your site, e.g. /blog
github_username:  rajnikhil

permalink:          /:year/:title.html

paginate: 4
paginate_path: "/page/:num"
comments: true

heading_font: Lobster 
about_footer: true
short_bio: >
    A day without laughter is a day wasted.
profile_picture: http://img3.rnkr-static.com/list_img/11570/111570/C300/movies-and-films-directed-by-charlie-chaplin-u4.jpg

google_analytics: true
tracking_id: UA-69243698-5

# Build settings | Do not edit anything below this
markdown: kramdown

gems:
  - jekyll-paginate

sass:
  style:            compressed
  sass_dir:         _sass

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
